Fix  Route.post() requires a callback function but got a [object Undefined]
B:\Projects\MERN_Sign-Up_and_Sign-In\backend\node_modules\express\lib\router\route.js:211
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (B:\Projects\MERN_Sign-Up_and_Sign-In\backend\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as post] (B:\Projects\MERN_Sign-Up_and_Sign-In\backend\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (B:\Projects\MERN_Sign-Up_and_Sign-In\backend\userRouter.js:9:8)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (B:\Projects\MERN_Sign-Up_and_Sign-In\backend\app.js:24:16)

Node.js v19.8.1
[nodemon] app crashed - waiting for file changes before starting...